// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIncidents = `-- name: CountIncidents :one
SELECT count(*)
FROM incidents i
JOIN categories c ON c.id = i.category_id
WHERE ($1::text = '' OR c.slug = $1::text)
    AND ($2::text = '' OR i.status::text = $2::text)
    AND ($3::text = '' OR EXISTS (
        SELECT 1
        FROM incident_tags it2
        JOIN tags t2 ON t2.id = it2.tag_id
        WHERE it2.incident_id = i.id AND t2.slug = $3::text
    ))
    AND ($4::text = '' OR i.title ILIKE '%' || $4::text || '%' OR i.summary ILIKE '%' || $4::text || '%')
`

type CountIncidentsParams struct {
	Category string `json:"category"`
	Status   string `json:"status"`
	Tag      string `json:"tag"`
	Query    string `json:"query"`
}

func (q *Queries) CountIncidents(ctx context.Context, arg CountIncidentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIncidents,
		arg.Category,
		arg.Status,
		arg.Tag,
		arg.Query,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listIncidents = `-- name: ListIncidents :many
SELECT
    i.id,
    i.title,
    i.slug,
    i.summary,
    i.status,
    i.created_at,
    i.updated_at,
    c.name AS category_name,
    c.slug AS category_slug,
    u.first_name AS author_first_name,
    u.last_name AS author_last_name,
    COALESCE(
        (SELECT array_agg(t.name ORDER BY t.name)
         FROM incident_tags it
         JOIN tags t ON t.id = it.tag_id
         WHERE it.incident_id = i.id),
        '{}'::text[]
    ) AS tags
FROM incidents i
JOIN categories c ON c.id = i.category_id
JOIN users u ON u.id = i.created_by
WHERE ($1::text = '' OR c.slug = $1::text)
    AND ($2::text = '' OR i.status::text = $2::text)
    AND ($3::text = '' OR EXISTS (
        SELECT 1
        FROM incident_tags it2
        JOIN tags t2 ON t2.id = it2.tag_id
        WHERE it2.incident_id = i.id AND t2.slug = $3::text
    ))
    AND ($4::text = '' OR i.title ILIKE '%' || $4::text || '%' OR i.summary ILIKE '%' || $4::text || '%')
ORDER BY i.created_at DESC
LIMIT $6 OFFSET $5
`

type ListIncidentsParams struct {
	Category   string `json:"category"`
	Status     string `json:"status"`
	Tag        string `json:"tag"`
	Query      string `json:"query"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type ListIncidentsRow struct {
	ID              int64              `json:"id"`
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Summary         pgtype.Text        `json:"summary"`
	Status          IncidentStatus     `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CategoryName    string             `json:"category_name"`
	CategorySlug    string             `json:"category_slug"`
	AuthorFirstName string             `json:"author_first_name"`
	AuthorLastName  string             `json:"author_last_name"`
	Tags            interface{}        `json:"tags"`
}

func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]ListIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listIncidents,
		arg.Category,
		arg.Status,
		arg.Tag,
		arg.Query,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncidentsRow
	for rows.Next() {
		var i ListIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
			&i.AuthorFirstName,
			&i.AuthorLastName,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
