// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type IncidentStatus string

const (
	IncidentStatusDraft     IncidentStatus = "draft"
	IncidentStatusPublished IncidentStatus = "published"
	IncidentStatusArchived  IncidentStatus = "archived"
)

func (e *IncidentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncidentStatus(s)
	case string:
		*e = IncidentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IncidentStatus: %T", src)
	}
	return nil
}

type NullIncidentStatus struct {
	IncidentStatus IncidentStatus `json:"incident_status"`
	Valid          bool           `json:"valid"` // Valid is true if IncidentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncidentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IncidentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncidentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncidentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncidentStatus), nil
}

// Files associated with an incident.
type Attachment struct {
	// Primary key.
	ID int64 `json:"id"`
	// Incident the attachment belongs to.
	IncidentID int64 `json:"incident_id"`
	// Original file name.
	Filename string `json:"filename"`
	// MIME type.
	Mime string `json:"mime"`
	// File size in bytes.
	Size int32 `json:"size"`
	// Storage path.
	Path string `json:"path"`
	// Creation date.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Technical domains used to group incidents.
type Category struct {
	// Primary key.
	ID int64 `json:"id"`
	// Category name.
	Name string `json:"name"`
	// URL identifier.
	Slug string `json:"slug"`
	// Category description.
	Description pgtype.Text `json:"description"`
}

// Central entity documenting a technical problem and its resolution.
type Incident struct {
	// Primary key.
	ID int64 `json:"id"`
	// Short title.
	Title string `json:"title"`
	// URL identifier.
	Slug string `json:"slug"`
	// Short overview.
	Summary pgtype.Text `json:"summary"`
	// Symptoms and observed behavior.
	Problem pgtype.Text `json:"problem"`
	// Investigation and reasoning.
	Diagnosis pgtype.Text `json:"diagnosis"`
	// Root cause.
	RootCause pgtype.Text `json:"root_cause"`
	// Resolution steps.
	Solution pgtype.Text `json:"solution"`
	// How to avoid recurrence.
	Prevention pgtype.Text `json:"prevention"`
	// Lifecycle state: draft, published or archived.
	Status IncidentStatus `json:"status"`
	// Category the incident belongs to.
	CategoryID int64 `json:"category_id"`
	// Author of the incident.
	CreatedBy int64 `json:"created_by"`
	// Creation date.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last update date.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Many-to-many relationship between incidents and tags.
type IncidentTag struct {
	// Referenced incident.
	IncidentID int64 `json:"incident_id"`
	// Referenced tag.
	TagID int64 `json:"tag_id"`
}

// External resources referenced by an incident.
type Link struct {
	// Primary key.
	ID int64 `json:"id"`
	// Incident the link belongs to.
	IncidentID int64 `json:"incident_id"`
	// Link title.
	Title string `json:"title"`
	// Link URL.
	Url string `json:"url"`
}

// Reusable code or command snippets attached to an incident.
type Snippet struct {
	// Primary key.
	ID int64 `json:"id"`
	// Incident the snippet belongs to.
	IncidentID int64 `json:"incident_id"`
	// Snippet title.
	Title string `json:"title"`
	// Language or format of the snippet content.
	Language string `json:"language"`
	// Snippet content.
	Content string `json:"content"`
	// Display order within the incident.
	Order int32 `json:"order"`
}

// Flexible keywords used to classify incidents.
type Tag struct {
	// Primary key.
	ID int64 `json:"id"`
	// Tag name.
	Name string `json:"name"`
	// URL identifier.
	Slug string `json:"slug"`
}

// Authenticated users of the application.
type User struct {
	// Primary key.
	ID int64 `json:"id"`
	// Unique email, used for authentication.
	Email string `json:"email"`
	// Hashed password.
	PasswordHash string `json:"password_hash"`
	// User firstname.
	FirstName string `json:"first_name"`
	// User lastname.
	LastName string `json:"last_name"`
	// Creation date.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Last update date.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Singleton row holding the instance configuration produced by the first-time setup wizard.
type Wizard struct {
	// Primary key.
	ID int64 `json:"id"`
	// Always true; the UNIQUE constraint on this column is what enforces the table can only ever hold one row.
	Singleton bool `json:"singleton"`
	// Display name of this Playbook instance.
	InstanceName string `json:"instance_name"`
	// IANA timezone used to display dates across the instance.
	Timezone string `json:"timezone"`
	// Default UI locale.
	Locale string `json:"locale"`
	// Date the setup wizard completed; the presence of this row means the instance is initialized.
	InitializedAt pgtype.Timestamptz `json:"initialized_at"`
}
