// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wizard.sql

package repo

import (
	"context"
)

const createWizard = `-- name: CreateWizard :one
INSERT INTO wizard (instance_name, timezone, locale)
VALUES ($1, $2, $3)
RETURNING id, singleton, instance_name, timezone, locale, initialized_at
`

type CreateWizardParams struct {
	InstanceName string `json:"instance_name"`
	Timezone     string `json:"timezone"`
	Locale       string `json:"locale"`
}

func (q *Queries) CreateWizard(ctx context.Context, arg CreateWizardParams) (Wizard, error) {
	row := q.db.QueryRow(ctx, createWizard, arg.InstanceName, arg.Timezone, arg.Locale)
	var i Wizard
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.InstanceName,
		&i.Timezone,
		&i.Locale,
		&i.InitializedAt,
	)
	return i, err
}

const deleteWizard = `-- name: DeleteWizard :exec
DELETE FROM wizard
`

func (q *Queries) DeleteWizard(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteWizard)
	return err
}

const getWizard = `-- name: GetWizard :one
SELECT id, singleton, instance_name, timezone, locale, initialized_at
FROM wizard
LIMIT 1
`

func (q *Queries) GetWizard(ctx context.Context) (Wizard, error) {
	row := q.db.QueryRow(ctx, getWizard)
	var i Wizard
	err := row.Scan(
		&i.ID,
		&i.Singleton,
		&i.InstanceName,
		&i.Timezone,
		&i.Locale,
		&i.InitializedAt,
	)
	return i, err
}
